sudo: false

language: python

services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# Use Python 3.7 on xenial with sudo since it's not available on trusty yet
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - docker pull opendxl/opendxl-broker
  - docker run -d -p 127.0.0.1:8883:8883 -p 127.0.0.1:8443:8443 opendxl/opendxl-broker
  - docker ps -a
  - pip install --upgrade pip	
  - pip install --upgrade pipenv  

install:
  - pip install .[test]

script:
  - python -m dxlclient provisionconfig dxlclient/test 127.0.0.1 client -u admin -p password
  - cp dxlclient/test/dxlclient.config dxlclient/test/client_config.cfg
  - sed -i -e "s/127.0.0.1;127.0.0.1/127.0.0.1/g" -e "/local/d" -e "/docker/d" dxlclient/test/client_config.cfg
  - cat dxlclient/test/client_config.cfg
  - echo Running tests with MQTT  
  - python setup.py ci
  - sed -i -e "s/= False/= True/g" -e "s/;8883/;443/g" -e "s/Brokers/BrokersWebSockets/g" dxlclient/test/client_config.cfg
  - cat dxlclient/test/client_config.cfg
  - echo Running tests with WebSockets  
  - python setup.py ci
